### ISSUE TITLE
在树莓派zero上，docker+OpenWRT，安装出现以下错误

### ISSUE THREAD

**Issue by kongh9** [WordsWorthLess/luci-app-v2ray#2]
~ # opkg install luci-app-v2ray_2.1.4_all.ipk 
Unknown package 'luci-app-v2ray'.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency ip for luci-app-v2ray
 * pkg_hash_check_unresolved: cannot find dependency kmod-nft-socket for luci-app-v2ray
 * pkg_hash_check_unresolved: cannot find dependency kmod-nft-tproxy for luci-app-v2ray
 * pkg_hash_check_unresolved: cannot find dependency resolveip for luci-app-v2ray
 * pkg_hash_check_unresolved: cannot find dependency dnsmasq-full for luci-app-v2ray
 * pkg_hash_check_unresolved: cannot find dependency curl for luci-app-v2ray
 * pkg_hash_check_unresolved: cannot find dependency coreutils-base64 for luci-app-v2ray
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-v2ray found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-v2ray.

**Comment by kongh9** [comment]
kuoruan那个可以安装成功，没有出现上面的错误。但是无法运行。

**Comment by WordsWorthLess** [comment]
你好，2.14是在kuoruan的luci-app-v2ray master分支的基础上修改，适用于OpenWRT 22.03及以上，使用基于nftables的firewall4防火墙的固件
你的给出的错误提示是缺少相关依赖包
请确保你的docker固件使用的是firewall4防火墙，并安装好以下依赖包（或者配置好包含以下程序的opkg源）
ip-full 或 ip-tiny
kmod-nft-socket
kmod-nft-tproxy
resolveip
dnsmasq-full (要求2.87以上版本，并编译时包含了nftset)
curl
coreutils-base64
