### ISSUE TITLE
默认配置下路由页面无法打开

### ISSUE THREAD

**Issue by iusearch** [WordsWorthLess/luci-app-v2ray#3]
RT，新安装后默认配置下打开路由页面显示 `y[0] is undefined`
OpenWrt 22.03.5，luci-app-v2ray v2.1.4

**Comment by WordsWorthLess** [comment]
抱歉，疏忽了，安装包自带的配置文件有两个小地方漏忘记补上tag了
1. 入站链接socks_proxy 未配置标识（tag)
2. DNS模块未配置标识(tag)
解决方法: 
进入Inbound(入站）配置页，点击socks_proxy这个入站后面的编辑按钮，然后在其它配置（Other Settings)页面，添加一个Tag
然后进入DNS配置页，在Tag选项中添加一个标识

又或者ssh进入路由器，输入:
uci set v2ray.socks_proxy.tag=socks_in
uci set v2ray.main_dns.tag=dns_server
uci commit v2ray

**Comment by iusearch** [comment]
解决了，谢谢
