### ISSUE TITLE
树莓派安装出现/etc/init.d/v2ray冲突

### ISSUE THREAD

**Issue by youland** [WordsWorthLess/luci-app-v2ray#4]
在线安装v2ray-core之后，发现装不了luci，说是/etc/init.d/v2ray下面有v2ray这个文件。
先装ludi，在线又无法安装v2ray-core。其实可以直接下载v2ray的二进制文件，但是没找到派的，无奈之下，先删了/etc/init.d/v2ray，在线安装v2ray-core，再把/etc/init.d/v2ray复制回去。

稍后测试能不能通。

**Comment by youland** [comment]
![Snipaste_2023-08-10_16-43-12](https://github.com/WordsWorthLess/luci-app-v2ray/assets/3339858/2addb0b6-0809-4ff6-ad42-66beb4703613)
![Snipaste_2023-08-10_16-44-25](https://github.com/WordsWorthLess/luci-app-v2ray/assets/3339858/e72cb0e1-1c51-438f-aba8-76ebd275164e)
![Snipaste_2023-08-10_16-44-46](https://github.com/WordsWorthLess/luci-app-v2ray/assets/3339858/f0b4ba72-3802-4525-98a9-f3a87098a931)
pi4上安装，出现以上问题。

**Comment by youland** [comment]
今天在一个全新的OpenWrt 23.05.0-rc3 x86_64的机子上操作
1，安装ipset,dnsmasq-full 2.89
2，把luci-app-v2ray_2.1.4_all.ipk上传到/tmp/tmp安装，出现以下错误
```
root@OpenWrt:~# cd /tmp/tmp
root@OpenWrt:/tmp/tmp# ls
luci-app-v2ray_2.1.4_all.ipk                luci-i18n-v2ray-zh-cn_230706.07333_all.ipk
root@OpenWrt:/tmp/tmp# opkg install luci-app-v2ray_*.ipk
Installing luci-app-v2ray (2.1.4) to root...
Installing kmod-nf-socket (5.15.127-1) to root...
Downloading https://mirror.sjtu.edu.cn/openwrt/releases/23.05.0-rc3/targets/x86/64/packages/kmod-nf-socket_5.15.127-1_x86_64.ipk
Installing kmod-nft-socket (5.15.127-1) to root...
Downloading https://mirror.sjtu.edu.cn/openwrt/releases/23.05.0-rc3/targets/x86/64/packages/kmod-nft-socket_5.15.127-1_x86_64.ipk
Installing kmod-nf-tproxy (5.15.127-1) to root...
Downloading https://mirror.sjtu.edu.cn/openwrt/releases/23.05.0-rc3/targets/x86/64/packages/kmod-nf-tproxy_5.15.127-1_x86_64.ipk
Installing kmod-nft-tproxy (5.15.127-1) to root...
Downloading https://mirror.sjtu.edu.cn/openwrt/releases/23.05.0-rc3/targets/x86/64/packages/kmod-nft-tproxy_5.15.127-1_x86_64.ipk
Installing resolveip (2) to root...
Downloading https://mirror.sjtu.edu.cn/openwrt/releases/23.05.0-rc3/packages/x86_64/base/resolveip_2_x86_64.ipk
Installing libnghttp2-14 (1.51.0-1) to root...
Downloading https://mirror.sjtu.edu.cn/openwrt/releases/23.05.0-rc3/packages/x86_64/packages/libnghttp2-14_1.51.0-1_x86_64.ipk
Installing libcurl4 (8.2.1-1) to root...
Downloading https://mirror.sjtu.edu.cn/openwrt/releases/23.05.0-rc3/packages/x86_64/packages/libcurl4_8.2.1-1_x86_64.ipk
Installing curl (8.2.1-1) to root...
Downloading https://mirror.sjtu.edu.cn/openwrt/releases/23.05.0-rc3/packages/x86_64/packages/curl_8.2.1-1_x86_64.ipk
Installing coreutils (9.3-1) to root...
Downloading https://mirror.sjtu.edu.cn/openwrt/releases/23.05.0-rc3/packages/x86_64/packages/coreutils_9.3-1_x86_64.ipk
Installing coreutils-base64 (9.3-1) to root...
Downloading https://mirror.sjtu.edu.cn/openwrt/releases/23.05.0-rc3/packages/x86_64/packages/coreutils-base64_9.3-1_x86_64.ipk
Configuring kmod-nf-tproxy.
Configuring kmod-nft-tproxy.
Configuring coreutils.
Configuring coreutils-base64.
Configuring resolveip.
Configuring kmod-nf-socket.
Configuring kmod-nft-socket.
Configuring libnghttp2-14.
Configuring libcurl4.
Configuring curl.
Configuring luci-app-v2ray.
Error: ipv4: FIB table does not exist.
Flush terminated
[err] Invalid V2Ray file.
[info] Transparent proxy disabled.
root@OpenWrt:/tmp/tmp#
```

**Comment by youland** [comment]
尝试如下
1，在线安装v2ray-core，然后手动删除
```
rm -rf /etc/config/v2ray
rm -rf /etc/init.d/v2ray
```
再安装luci，FIB不报错了，可以正常安装。

2，但是，outbound页面一直报错，有一次能显示，但不能保存配置。
![Snipaste_2023-08-22_10-27-25](https://github.com/WordsWorthLess/luci-app-v2ray/assets/3339858/2151cc4b-b0b2-49bc-97a9-6017de42c1cb)

**Comment by WordsWorthLess** [comment]
> 尝试如下 1，在线安装v2ray-core，然后手动删除
> 
> ```
> rm -rf /etc/config/v2ray
> rm -rf /etc/init.d/v2ray
> ```
> 
> 再安装luci，FIB不报错了，可以正常安装。
> 
> 2，但是，outbound页面一直报错，有一次能显示，但不能保存配置。 ![Snipaste_2023-08-22_10-27-25](https://user-images.githubusercontent.com/3339858/262202499-2151cc4b-b0b2-49bc-97a9-6017de42c1cb.png)

              抱歉，疏忽了，安装包自带的配置文件有两个小地方漏忘记补上tag了
1. 入站链接socks_proxy 未配置标识（tag)
2. DNS模块未配置标识(tag)
解决方法: 
进入Inbound(入站）配置页，点击socks_proxy这个入站后面的编辑按钮，然后在其它配置（Other Settings)页面，添加一个Tag
然后进入DNS配置页，在Tag选项中添加一个标识

又或者ssh进入路由器，输入:
uci set v2ray.socks_proxy.tag=socks_in
uci set v2ray.main_dns.tag=dns_server
uci commit v2ray

_Originally posted by @WordsWorthLess in https://github.com/WordsWorthLess/luci-app-v2ray/issues/3#issuecomment-1646039904_

**Comment by youland** [comment]
可以了，完美解决。

建议如下：
1，建议先安装v2ray-core.ipk(可能有一些依赖包需要一起安装，只安装core的二进制文件，可能会少一些依赖包，导致启动不了)，再删除core自动配置的两个文件，分别是：/etc/config/v2ray和/etc/init.d/v2ray，因为这两个文件和luci自带的有冲突。
2，或者建议，在luci里面，开头就加上删除命令，把这两个文件给删掉，这样最省事。

**Comment by youland** [comment]
兄弟，你电报id是什么，邮件发给我，还有点小问题想加电报请教一下，我邮箱：eW91bGFuZDgxNjhAZ21haWwuY29t
base64解码即可。
