### ISSUE TITLE
gfwlist模式无法代理电报的IP列表

### ISSUE THREAD

**Issue by youland** [WordsWorthLess/luci-app-v2ray#5]
由于电报的客户端是IP，只能额外的来代理。
当选gfwlist模式时，额外代理的ip列表不生效。
选直连中国就可以用。
![Snipaste_2023-08-24_08-47-10](https://github.com/WordsWorthLess/luci-app-v2ray/assets/3339858/f54d3f61-406f-407f-a57f-42683bb7952b)
![Snipaste_2023-08-24_08-47-19](https://github.com/WordsWorthLess/luci-app-v2ray/assets/3339858/15cfe29b-fd66-4f16-9264-ea5c926f62e7)

直连中国模式，可以成功代理ip列表。
![Snipaste_2023-08-24_08-47-34](https://github.com/WordsWorthLess/luci-app-v2ray/assets/3339858/863895cc-8051-4a1f-9f81-e43c81c28395)

**Comment by WordsWorthLess** [comment]
因为电报IP属于境外IP,所以直连中国IP模式可以代理电报的IP
代码有bug
ssh连接到路由器
输入如下代码可以解决
```
sed -i 's/echo \"$proxy_content\"/echo $proxy_content/g' /etc/init.d/v2ray 
```

**Comment by WordsWorthLess** [comment]
因为电报IP属于境外IP,所以直连中国IP可以代理其IP地址
我这里测试 ,gfwlist模式 可以看到额外代理列表里的IP地址能正确添加到代理的IP集合里面
你试试输入nft list set inet v2ray v2ray_dst_proxy_v4 ,看看有没有你添加进去的IP地址
![extra_proxy](https://github.com/WordsWorthLess/luci-app-v2ray/assets/25536918/0ebf534f-1fd8-4e60-8f99-9d9fbef153fc)

**Comment by youland** [comment]
兄弟，又报错FIB表不存在，可能是这个原因，导致ipv4无法额外代理。

```
root@OpenWrt:~# /etc/init.d/v2ray reload
Error: ipv4: FIB table does not exist.
Flush terminated
[info] Routing disabled: main_routing
[info] Policy disabled: main_policy
[info] Reverse disabled: main_reverse
[info] Setting transparent proxy on port: 2000
[info] Transparent proxy mode: gfwlist_proxy
/etc/rc.common: line 1216: can't create 91.108.4.0/22
91.108.56.0/22
109.239.140.0/24
149.154.160.0/20
149.154.175.50/31
194.14.177.0/24
194.68.28.0/23
194.68.30.0/24
194.132.172.0/24
194.132.162.0/24
193.182.7.0/24: nonexistent directory
Error: conflicting intervals specified
add element inet v2ray v2ray_dst_proxy_v4 { 91.108.4.0/22, 91.108.56.0/22, 109.239.140.0/24, 149.154.160.0/20, 149.154.175.50/31, 194.14.177.0/24, 194.68.28.0/23, 194.68.30.0/24, 194.132.172.0/24, 194.132.162.0/24, 193.182.7.0/24 }
                                                                                             ~~~~~~~~~~~~~~~~  ^^^^^^^^^^^^^^^^^
[info] Restarting dnsmasq...
root@OpenWrt:~#
```
![Snipaste_2023-08-27_09-19-13](https://github.com/WordsWorthLess/luci-app-v2ray/assets/3339858/ffa62183-58de-4ada-895e-f2a6d2c04305)

里面没有内容

```
root@OpenWrt:~# nft list set inet v2ray v2ray_dst_proxy_v4
table inet v2ray {
        set v2ray_dst_proxy_v4 {
                type ipv4_addr
                flags interval
        }
}
```

![Snipaste_2023-08-27_09-19-26](https://github.com/WordsWorthLess/luci-app-v2ray/assets/3339858/f8342d92-abdd-4a6b-bd7c-c8d2f6ab50ef)

**Comment by youland** [comment]
经过测试，本机开启ipv6无法正常代理，关闭ipv6后，一切正常。
另外，电报的ip地址，添加报错。
![1](https://github.com/WordsWorthLess/luci-app-v2ray/assets/3339858/c42b966c-df98-4561-b9c8-7294705067b3)
![2](https://github.com/WordsWorthLess/luci-app-v2ray/assets/3339858/5b212db8-e701-477a-8135-5ea635338ed6)

打开ipv6，切换为直连cn，一切正常
![3](https://github.com/WordsWorthLess/luci-app-v2ray/assets/3339858/e7121865-90ad-45b8-a0b2-529e58d78a93)

**Comment by WordsWorthLess** [comment]
FIB tables does not exist 这个报错应该是你采用redirect模式来进行代理(即不勾选 **使用TProxy方式**)
重载服务会有一条命令, 删除路由表的规则,以及删除路由表,因为redirect不添加路由表,所以删除路由表会报错,其实并不影响
我忘记把报错信息给处理了, 你把
[/etc/init.d/v2ray第1041行](https://github.com/WordsWorthLess/luci-app-v2ray/blob/9a9ba5ab5800f86ecd0bba3929662d0b2b9b3fdc/public/root/etc/init.d/v2ray#L1041)
修改为
```
  ip route flush table 100 2>/dev/null
```
就能忽略报错了

IPv6的代理问题, WIN 11的网络是IPv6优先的, 如果你的网络的IPv6地址通过无状态方式配置, 那么网关 DNS等配置等均通过路由通告自动配置, 无法将IPv6网关指向路由器, 无法正确代理IPv6流量, 这就涉及到IPv6配置的相关知识, 不在此讨论了, 你可以在路由器的web配置页面进入:
网络 >>DHCP/DNS >> 高级配置 >> 过滤 IPv6 AAAA 记录, 这样就不会有IPv6的解析(但是也会导致访问不了IPv6 Only的网站)

至于/etc/rc.common line: 1216的问题, 你的openwrt使用的是基于nftables的 firewall4,应该是不会执行这行命令的, 我这里测试了使用正常, 估计代码还有不少BUG , 我有空再修修
<img width="736" alt="redirect" src="https://github.com/WordsWorthLess/luci-app-v2ray/assets/25536918/fd978a11-0e75-4476-b7d1-c3d822cbc048">

**Comment by youland** [comment]
好的，谢谢大佬。
感觉可以把目前这些问题修修出一版了，期待。
1，入站和路由少了tag
2，FIB报错
3，安装luci时先删除v2ray-core的配置文件（删除命令可否加在脚本里执行？）

**Comment by jerry-ch-issue** [comment]
的确是无法添加额外代理列表的IP，需要在/init.d/v2ray 中 1109 行开始，每个

`flags interval` 
下一行添加
 `auto-merge`。

**Comment by youland** [comment]
> 的确是无法添加额外代理列表的IP，需要在/init.d/v2ray 中 1109 行开始，每个
> 
> `flags interval` 下一行添加 `auto-merge`。

试了一下，确实可以了。

但是openwrt开启ipv6+只代理gfwlist还是不行，纯ipv4是没有问题了。

**Comment by jerry-ch-issue** [comment]
> > 的确是无法添加额外代理列表的IP，需要在/init.d/v2ray 中 1109 行开始，每个
> > `flags interval` 下一行添加 `auto-merge`。
> 
> 试了一下，确实可以了。
> 
> 但是openwrt开启ipv6+只代理gfwlist还是不行，纯ipv4是没有问题了。

这个网络环境的影响比较大，我的生产环境是 openwrt 拨号，不过还停在了 21.02 的版本，所以用了原 kuouran 的版本。
按理来讲这种网络环境下，lan口默认已经  **_通告该设备为 IPv6 DNS 服务器_** 勾选了。所以能将 ipv6 的 DNS 流量导入到dnsmasq，然后触发 dnsmasq 解析的转发规则指向 v2ray 透明代理模块中指定的代理列表 DNS，而后触发 ipset。这其实解决了整个链路中从设备到路由器的问题。因为我的机场只有 v4，所以我的代理列表 DNS 指向的是 smartdns，因为 smartdns 能过滤 AAAA 的解析（我研究了一下 dnsmasq 2.87 之后新增的过滤 v4 或者 v6 解析的功能，发现只能全部过滤或者全部放行，不能指定域名或者列表，所以只能继续使用smartdns）。
我用虚拟机测试了23.05，用了[WordsWorthLess](https://github.com/WordsWorthLess)的版本。因为是虚拟机，所以只能使用旁路由模式。在旁路由模式下，需要将终端设备的 v4 和 v6 的网关和 DNS 都指向旁路由。旁路由还需要新增 lan6， 协议是DHCPv6客户端，以让旁路由获得 v6 地址。终端设备 ipv6 的 DNS 设置为旁路由 lan 口的 fd 开头 :1 结尾的那个 v6 就行（我的旁路由有两个 fd 开头的 v6 地址，注意要用和主路由的 lan 口前缀一致的那个）。

**Comment by jerry-ch-issue** [comment]
还需要将 lan6 加入透明代理的 lan 接口中。

**Comment by youland** [comment]
> 还需要将 lan6 加入透明代理的 lan 接口中。

兄弟留个电报账号，有事请教。我的电报
eW91bGFuZA==

**Comment by jerry-ch-issue** [comment]
电报不是刚需，之前国内号码不能使用后已经放弃了。
