### ISSUE TITLE
luci v2ray - global settings 页面报错

### ISSUE THREAD

**Issue by synebula** [WordsWorthLess/luci-app-v2ray#6]
报错内容: TypeError Cannot convert undefined or null to object.
页面空白无显示内容

软件版本：
OpenWrt 22.03.5 r20134-5f15225c1e
v2ray-core | 5.7.0-1
luci-app-v2ray | 2.1.4

同时 System Log 无相关错误内容， 大佬看下啥情况？

**Comment by youland** [comment]
截个图上来看看

**Comment by synebula** [comment]
> 截个图上来看看

@youland 
截图已上传，麻烦了

![capture_20230824214820807](https://github.com/WordsWorthLess/luci-app-v2ray/assets/17894393/90404655-5aaa-4bfc-89d8-32c57a9a20d5)

**Comment by youland** [comment]
https://github.com/WordsWorthLess/luci-app-v2ray/issues/3
试下这个方法看能不能解决。

**Comment by synebula** [comment]
> #3 试下这个方法看能不能解决。

@youland 谢谢帮助，我折腾了一下，好像是配置文件冲突搞得没使用正确的文件。

但现在还是有问题，就很奇怪。

Outbinding 和 Routing 两个页面都报这个错：

![image](https://github.com/WordsWorthLess/luci-app-v2ray/assets/17894393/8fdc1b4e-4f43-4028-a60f-e46b05046394)

**Comment by youland** [comment]
作者安装包自带的配置文件有两个小地方漏忘记补上tag了

1,入站链接socks_proxy 未配置标识（tag)
2,DNS模块未配置标识(tag)
解决方法:
进入Inbound(入站）配置页，点击socks_proxy这个入站后面的编辑按钮，然后在其它配置（Other Settings)页面，添加一个Tag
然后进入DNS配置页，在Tag选项中添加一个标识
又或者ssh进入路由器，输入:
uci set v2ray.socks_proxy.tag=socks_in
uci set v2ray.main_dns.tag=dns_server
uci commit v2ray

**Comment by synebula** [comment]
> 作者安装包自带的配置文件有两个小地方漏忘记补上tag了
> 
> 1,入站链接socks_proxy 未配置标识（tag) 2,DNS模块未配置标识(tag) 解决方法: 进入Inbound(入站）配置页，点击socks_proxy这个入站后面的编辑按钮，然后在其它配置（Other Settings)页面，添加一个Tag 然后进入DNS配置页，在Tag选项中添加一个标识 又或者ssh进入路由器，输入: uci set v2ray.socks_proxy.tag=socks_in uci set v2ray.main_dns.tag=dns_server uci commit v2ray

@youland 
这个解决第一个问题的时候操作了，第一个命令就报错了...  以为没用
刚操作确实靠这个解决了低二个问题，谢谢。

现在又是无法启动，Save/Reload都点了，没有反应

![image](https://github.com/WordsWorthLess/luci-app-v2ray/assets/17894393/72ed4c5f-1831-4f50-90f4-ca377f2f9978)

跟版本有关么？

**Comment by youland** [comment]
![Snipaste_2023-08-25_16-01-50](https://github.com/WordsWorthLess/luci-app-v2ray/assets/3339858/ec05abd8-8cc9-426a-8c6b-3255ee0e18ad)
你参考一下我的

**Comment by synebula** [comment]
> ![Snipaste_2023-08-25_16-01-50](https://user-images.githubusercontent.com/3339858/263207384-ec05abd8-8cc9-426a-8c6b-3255ee0e18ad.png) 你参考一下我的

![image](https://github.com/WordsWorthLess/luci-app-v2ray/assets/17894393/10817776-7b9f-4e52-872e-6064952b6da8)

@youland 核对了下没啥问题啊，Assets location 手动补充上了。

**Comment by synebula** [comment]
@youland 
谢谢，解决了。 看了下日志，发现是加载geoip数据出错，这个包我没装...
总之，谢谢帮助！
