### ISSUE TITLE
在23.05.Xoutbound 和 Routing 界面报错

### ISSUE THREAD

**Issue by jerry-ch-issue** [WordsWorthLess/luci-app-v2ray#8]
用的是老的 4.45.2 的 v2ray 内核，不过这个应该对这个错误没有影响吧。
![image](https://github.com/WordsWorthLess/luci-app-v2ray/assets/65878337/a8dd158c-2b89-4f63-abc3-686f36f478c2)
没在使用环境中测试，windows 中开了个虚拟机测试了一下。主要是想试试，没有其他DNS工具的介入下，新版 dnsmasq 能不能实现需代理列表只返回ipv4。
其他正常，，，gfwlist 正常更新，没有报错了。感谢您。
![image](https://github.com/WordsWorthLess/luci-app-v2ray/assets/65878337/6f81abb7-2cb0-43bd-93ec-415cb31adbc4)

**Comment by WordsWorthLess** [comment]
在23.05.X可以正常運行的,配置文件的BUG 
解決辦法:
https://github.com/WordsWorthLess/luci-app-v2ray/issues/3#issuecomment-1646039904

**Comment by jerry-ch-issue** [comment]
谢谢，问题解决
